#https://www.tpisoftware.com/tpu/articleDetails/1826
version: "3.7"

services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: read_server
    # restart: always
    environment:
      - APP_NAME=FlaskApp
    ports:
      - 5555:5555
    depends_on:
      - db
    restart: always

  db:
    build:
      context: ./sqldata
      dockerfile: Dockerfile
    container_name: read_postgresql
    restart: always
    environment:
      - POSTGRES_PASSWORD=root

    ports:
      - 5432:5432
    #資料持久化與本機共享資料夾
    #volumes:
    #  - ./sqldata:/docker-entrypoint-initdb.d