"""init

Revision ID: 5bb2e36eea8e
Revises: 
Create Date: 2023-06-30 11:52:11.101743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb2e36eea8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('CategoryId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CategoryName', sa.String(), nullable=True),
    sa.Column('CreateUser', sa.String(), nullable=True),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('UpdateUser', sa.String(), nullable=True),
    sa.Column('UpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('CategoryId')
    )
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Category_CategoryId'), ['CategoryId'], unique=False)

    op.create_table('Read',
    sa.Column('ReadId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('URL', sa.String(), nullable=True),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Describe', sa.String(), nullable=True),
    sa.Column('Star', sa.Integer(), nullable=True),
    sa.Column('CategoryId', sa.Integer(), nullable=True),
    sa.Column('Read', sa.Boolean(), nullable=False),
    sa.Column('CreateUser', sa.String(), nullable=True),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('UpdateUser', sa.String(), nullable=True),
    sa.Column('UpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ReadId')
    )
    with op.batch_alter_table('Read', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Read_ReadId'), ['ReadId'], unique=False)

    op.create_table('Remain',
    sa.Column('RemainId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReadNum', sa.Integer(), nullable=False),
    sa.Column('ReadTime', sa.Integer(), nullable=False),
    sa.Column('RemainTime', sa.Time(), nullable=False),
    sa.Column('CreateUser', sa.String(), nullable=True),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('UpdateUser', sa.String(), nullable=True),
    sa.Column('UpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('RemainId')
    )
    with op.batch_alter_table('Remain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Remain_RemainId'), ['RemainId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Remain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Remain_RemainId'))

    op.drop_table('Remain')
    with op.batch_alter_table('Read', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Read_ReadId'))

    op.drop_table('Read')
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Category_CategoryId'))

    op.drop_table('Category')
    # ### end Alembic commands ###
